"""Typed API schemas for the profile/account vertical slice."""

from app.schemas.account import AccountCreate, AccountRead, AccountUpdate, IssuerCode
from app.schemas.budget import BudgetCreate, BudgetRead, BudgetUpdate
from app.schemas.category import CategoryCreate, CategoryRead, CategoryUpdate
from app.schemas.imports import (
    ImportBatchCreate,
    ImportBatchRead,
    ImportCancelResponse,
    ImportCandidateResponse,
    ImportCommitRequest,
    ImportCommitResponse,
    ImportDetailResponse,
    ImportErrorResponse,
    ImportNotFoundResponse,
    ImportPreviewResponse,
    ImportStagedTransactionCreate,
    ImportStagedTransactionRead,
    ImportTransactionLinkCreate,
    ImportTransactionLinkRead,
    ImportWarningCreate,
    ImportWarningRead,
    ImportWarningResponse,
)
from app.schemas.income import (
    IncomeOccurrenceRead,
    IncomeScheduleCreate,
    IncomeScheduleRead,
    IncomeScheduleUpdate,
    IncomeSummaryRead,
)
from app.schemas.merchant_rule import (
    MerchantRuleApplyResult,
    MerchantRuleCreate,
    MerchantRuleLearnResult,
    MerchantRuleRead,
    MerchantRuleUpdate,
)
from app.schemas.profile import ProfileCreate, ProfileRead, ProfileUpdate
from app.schemas.recurring import (
    RecurringDetectResult,
    RecurringSeriesRead,
    RecurringSeriesUpdate,
    RecurringStatus,
)
from app.schemas.transaction import (
    SplitInput,
    SplitRead,
    TagCreate,
    TagRead,
    TransactionBulkAction,
    TransactionBulkCategorize,
    TransactionBulkResult,
    TransactionBulkSpendingInclusion,
    TransactionCreate,
    TransactionDeletedRead,
    TransactionDetailRead,
    TransactionRead,
    TransactionSplitsReplace,
    TransactionTagsReplace,
    TransactionType,
    TransactionUpdate,
)

__all__ = [
    "AccountCreate",
    "AccountRead",
    "AccountUpdate",
    "BudgetCreate",
    "BudgetRead",
    "BudgetUpdate",
    "CategoryCreate",
    "CategoryRead",
    "CategoryUpdate",
    "IssuerCode",
    "IncomeOccurrenceRead",
    "IncomeScheduleCreate",
    "IncomeScheduleRead",
    "IncomeScheduleUpdate",
    "IncomeSummaryRead",
    "MerchantRuleApplyResult",
    "MerchantRuleCreate",
    "MerchantRuleLearnResult",
    "MerchantRuleRead",
    "MerchantRuleUpdate",
    "ImportBatchCreate",
    "ImportBatchRead",
    "ImportCancelResponse",
    "ImportCandidateResponse",
    "ImportCommitRequest",
    "ImportCommitResponse",
    "ImportDetailResponse",
    "ImportErrorResponse",
    "ImportNotFoundResponse",
    "ImportPreviewResponse",
    "ImportStagedTransactionCreate",
    "ImportStagedTransactionRead",
    "ImportTransactionLinkCreate",
    "ImportTransactionLinkRead",
    "ImportWarningCreate",
    "ImportWarningRead",
    "ImportWarningResponse",
    "ProfileCreate",
    "ProfileRead",
    "ProfileUpdate",
    "RecurringDetectResult",
    "RecurringSeriesRead",
    "RecurringSeriesUpdate",
    "RecurringStatus",
    "SplitInput",
    "SplitRead",
    "TagCreate",
    "TagRead",
    "TransactionBulkAction",
    "TransactionBulkCategorize",
    "TransactionBulkResult",
    "TransactionBulkSpendingInclusion",
    "TransactionCreate",
    "TransactionDeletedRead",
    "TransactionDetailRead",
    "TransactionRead",
    "TransactionSplitsReplace",
    "TransactionTagsReplace",
    "TransactionType",
    "TransactionUpdate",
]
