"""Typed API schemas for the profile/account vertical slice."""

from app.schemas.account import AccountCreate, AccountRead, AccountUpdate, IssuerCode
from app.schemas.category import CategoryCreate, CategoryRead, CategoryUpdate
from app.schemas.imports import (
    ImportBatchCreate,
    ImportBatchRead,
    ImportCancelResponse,
    ImportCandidateResponse,
    ImportCommitRequest,
    ImportCommitResponse,
    ImportDetailResponse,
    ImportErrorResponse,
    ImportNotFoundResponse,
    ImportPreviewResponse,
    ImportStagedTransactionCreate,
    ImportStagedTransactionRead,
    ImportTransactionLinkCreate,
    ImportTransactionLinkRead,
    ImportWarningCreate,
    ImportWarningRead,
    ImportWarningResponse,
)
from app.schemas.profile import ProfileCreate, ProfileRead, ProfileUpdate
from app.schemas.transaction import (
    SplitInput,
    SplitRead,
    TagCreate,
    TagRead,
    TransactionBulkAction,
    TransactionBulkCategorize,
    TransactionBulkResult,
    TransactionBulkSpendingInclusion,
    TransactionCreate,
    TransactionDeletedRead,
    TransactionDetailRead,
    TransactionRead,
    TransactionSplitsReplace,
    TransactionTagsReplace,
    TransactionType,
    TransactionUpdate,
)

__all__ = [
    "AccountCreate",
    "AccountRead",
    "AccountUpdate",
    "CategoryCreate",
    "CategoryRead",
    "CategoryUpdate",
    "IssuerCode",
    "ImportBatchCreate",
    "ImportBatchRead",
    "ImportCancelResponse",
    "ImportCandidateResponse",
    "ImportCommitRequest",
    "ImportCommitResponse",
    "ImportDetailResponse",
    "ImportErrorResponse",
    "ImportNotFoundResponse",
    "ImportPreviewResponse",
    "ImportStagedTransactionCreate",
    "ImportStagedTransactionRead",
    "ImportTransactionLinkCreate",
    "ImportTransactionLinkRead",
    "ImportWarningCreate",
    "ImportWarningRead",
    "ImportWarningResponse",
    "ProfileCreate",
    "ProfileRead",
    "ProfileUpdate",
    "SplitInput",
    "SplitRead",
    "TagCreate",
    "TagRead",
    "TransactionBulkAction",
    "TransactionBulkCategorize",
    "TransactionBulkResult",
    "TransactionBulkSpendingInclusion",
    "TransactionCreate",
    "TransactionDeletedRead",
    "TransactionDetailRead",
    "TransactionRead",
    "TransactionSplitsReplace",
    "TransactionTagsReplace",
    "TransactionType",
    "TransactionUpdate",
]
